import java.lang.*;
import java.util.*;

class Main{
    public static void main(String[] args) {
        String str;
        Scanner sc=new Scanner(System.in);
        System.out.print("Enter the message: ");
        str=sc.nextLine();
        Huffman huffman=new Huffman();
        String code=huffman.encode(str);
        //This is the code generated by the encoder.
        System.out.println(code);
        //This is the decoded message.
        System.out.println(huffman.decode(code));
    }
}
